name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 337593502545.dkr.ecr.us-east-2.amazonaws.com/boilertalk/alpine-docker-ssh-client:$(date +%s)
    - name: ECR Login & Push
      uses: actions/aws/cli@master
      env:
        AWS_DEFAULT_REGION: us-east-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IMAGE_URI: 337593502545.dkr.ecr.us-east-2.amazonaws.com/boilertalk/alpine-docker-ssh-client
      with:
        entrypoint: /bin/bash
        args: '-c "aws ecr get-login --no-include-email | sh && docker push $IMAGE_URI"'
