name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: boilertalk/alpine-docker-ssh-client/alpine-docker-ssh-client:${{ github.sha }}
        username: github
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
    - name: Tag latest docker image
      run: >
        if [ $GITHUB_REF == "refs/heads/master" ]; then
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username github --password-stdin
          docker tag docker.pkg.github.com/boilertalk/alpine-docker-ssh-client/alpine-docker-ssh-client:$GITHUB_SHA docker.pkg.github.com/boilertalk/alpine-docker-ssh-client/alpine-docker-ssh-client:latest;
          docker push docker.pkg.github.com/boilertalk/alpine-docker-ssh-client/alpine-docker-ssh-client:latest;
        fi
    - name: Secure Actions Webhook
      uses: Ybrin/secure-actions-webhook@0.1.2
      env:
        REQUEST_URI: https://kube-cd.volkncloud.com/
        HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
        REQUEST_DATA: '{ "github": ${{ toJson(github)}}, "image": "docker.pkg.github.com/boilertalk/alpine-docker-ssh-client/alpine-docker-ssh-client" }'

