name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boilertalk/alpine-docker-ssh-client:$(date +%s)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: boilertalk/alpine-docker-ssh-client
        username: AWS
        password: ${{ secrets.AWS_REGISTRY_TOKEN }}
        registry: ${{ secrets.AWS_REGISTRY_URL }}
